services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_user_password
    ports:
      - "3306:3306"
    